FROM python:3.11-slim

WORKDIR /app
COPY requirements.txt /app/

RUN apt-get update && apt-get install -y \
    build-essential \
    && pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt \
    && apt-get remove -y build-essential \
    && apt-get autoremove -y \
    && apt-get clean

COPY . /app

EXPOSE 5000
CMD ["python", "server.py"]